name: 'Go Proxy Cache Updater'
description: 'Pull the new release of a module to the Go proxy cache'
author: 'Nicholas Fedor'
inputs:
  goproxy:
    description: 'URL of the proxy to be passed to `go get` as GOPROXY='
    required: false
    default: 'https://proxy.golang.org'
  import_path:
    description: 'Package import path. If not set, github.com/<user>/<repo> is used as a default'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'download'
  color: 'blue'
